### ISSUE TITLE
help

### ISSUE THREAD

**Issue by D00oo00M** [Viblast/dash-proxy#11]
hi im beginner in python, can someone make a guide how to run this script??
i search and dont found any guide on internet how to use this script

**Comment by przemyslaw-gorszkowski-red** [comment]
Simple case: "python dashproxy.py link_to_manifest", more option you can get with:"python dashproxy.py -h"
Of course you have to have python installed on your system,

**Comment by D00oo00M** [comment]
> Simple case: "python dashproxy.py link_to_manifest", more option you can get with:"python dashproxy.py -h"
> Of course you have to have python installed on your system,

this is what i get:
Traceback (most recent call last):
File "dashproxy.py", line 8, in 
import requests
ImportError: No module named 'requests'

**Comment by przemyslaw-gorszkowski-red** [comment]
https://stackoverflow.com/questions/17309288/importerror-no-module-named-requests

**Comment by przemyslaw-gorszkowski-red** [comment]
Also keep in mind that dashproxy does not support whole MPEG-DASH specification, which means it does not parse, download streams for all type of manifests.

**Comment by yolanda123a** [comment]
> 
> 
> Simple case: "python dashproxy.py link_to_manifest", more option you can get with:"python dashproxy.py -h"
> Of course you have to have python installed on your system,

hey have this issue can you tell me somthing how fix

python ./dashproxy.py https://------.mpd -o. -d
Running dash proxy for stream https://-------.mpd. Output goes in .
mpd=[<Element '{urn:mpeg💨schema:mpd:2011}Period' at 0x0000023B3BC46310>]
Starting a downloader for Representation (period=0 adaptation-set=0 representation=0)
Traceback (most recent call last):
File "D:\Jonathan\Programas\Video_Encriptado\cmder_mini\dashproxy.py", line 289, in
main()
File "D:\Jonathan\Programas\Video_Encriptado\cmder_mini\dashproxy.py", line 286, in main
run(args)
File "D:\Jonathan\Programas\Video_Encriptado\cmder_mini\dashproxy.py", line 275, in run
return proxy.run()
File "D:\Jonathan\Programas\Video_Encriptado\cmder_mini\dashproxy.py", line 115, in run
self.refresh_mpd()
File "D:\Jonathan\Programas\Video_Encriptado\cmder_mini\dashproxy.py", line 129, in refresh_mpd
self.handle_mpd(mpd)
File "D:\Jonathan\Programas\Video_Encriptado\cmder_mini\dashproxy.py", line 155, in handle_mpd
self.ensure_downloader(mpd, rep_addr)
File "D:\Jonathan\Programas\Video_Encriptado\cmder_mini\dashproxy.py", line 173, in ensure_downloader
downloader.handle_mpd(mpd, self.get_base_url(mpd))
File "D:\Jonathan\Programas\Video_Encriptado\cmder_mini\dashproxy.py", line 204, in handle_mpd
segment_timeline = self.mpd.segment_timeline(self.rep_addr)
File "D:\Jonathan\Programas\Video_Encriptado\cmder_mini\dashproxy.py", line 77, in segment_timeline
return self.segment_template(rep_addr).find('mpd:SegmentTimeline', ns)
AttributeError: 'NoneType' object has no attribute 'find'
