### ISSUE TITLE
error none type

### ISSUE THREAD

**Issue by yolanda123a** [Viblast/dash-proxy#17]
i have this error
have pyhton pip dependences installed
what more should install for this program work like should be work WITHOUT errors
thanks

python ./dashproxy.py https://------.mpd -o. -d
Running dash proxy for stream https://-------.mpd. Output goes in .
mpd=[<Element '{urn:mpeg:dash:schema:mpd:2011}Period' at 0x0000023B3BC46310>]
Starting a downloader for Representation (period=0 adaptation-set=0 representation=0)
Traceback (most recent call last):
  File "D:\Jonathan\Programas\Video_Encriptado\cmder_mini\dashproxy.py", line 289, in <module>
    main()
  File "D:\Jonathan\Programas\Video_Encriptado\cmder_mini\dashproxy.py", line 286, in main
    run(args)
  File "D:\Jonathan\Programas\Video_Encriptado\cmder_mini\dashproxy.py", line 275, in run
    return proxy.run()
  File "D:\Jonathan\Programas\Video_Encriptado\cmder_mini\dashproxy.py", line 115, in run
    self.refresh_mpd()
  File "D:\Jonathan\Programas\Video_Encriptado\cmder_mini\dashproxy.py", line 129, in refresh_mpd
    self.handle_mpd(mpd)
  File "D:\Jonathan\Programas\Video_Encriptado\cmder_mini\dashproxy.py", line 155, in handle_mpd
    self.ensure_downloader(mpd, rep_addr)
  File "D:\Jonathan\Programas\Video_Encriptado\cmder_mini\dashproxy.py", line 173, in ensure_downloader
    downloader.handle_mpd(mpd, self.get_base_url(mpd))
  File "D:\Jonathan\Programas\Video_Encriptado\cmder_mini\dashproxy.py", line 204, in handle_mpd
    segment_timeline = self.mpd.segment_timeline(self.rep_addr)
  File "D:\Jonathan\Programas\Video_Encriptado\cmder_mini\dashproxy.py", line 77, in segment_timeline
    return self.segment_template(rep_addr).find('mpd:SegmentTimeline', ns)
AttributeError: 'NoneType' object has no attribute 'find'

**Comment by yolanda123a** [comment]
why noone answer???????????????????????????????????

**Comment by przemyslaw-gorszkowski-red** [comment]
Can you provide a manifest for which you tried to run the dashproxy? It looks that dashproxy can't find "SegmentTemplate" in Adaptation or Representation.

**Comment by kevan1** [comment]
https://cdn-videos.flowlikemusic.com/files/videos/e125e3ef-912b-44ab-9a56-69593ab4d1cd/master.mpd

**Comment by przemyslaw-gorszkowski-red** [comment]
For this manifest I get different error:
Running dash proxy for stream https://cdn-videos.flowlikemusic.com/files/videos/e125e3ef-912b-44ab-9a56-69593ab4d1cd/master.mpd. Output goes in .
mpd=[<Element '{urn:mpeg:dash:schema:mpd:2011}Period' at 0x7f041f1054a8>]
Starting a downloader for Representation (period=0 adaptation-set=0 representation=0)
requesting master_hdinit.cmfv from https://cdn-videos.flowlikemusic.com/files/videos/e125e3ef-912b-44ab-9a56-69593ab4d1cd/master_hdinit.cmfv
Traceback (most recent call last):
  File "dashproxy.py", line 289, in <module>
    main()
  File "dashproxy.py", line 286, in main
    run(args)
  File "dashproxy.py", line 275, in run
    return proxy.run()
  File "dashproxy.py", line 115, in run
    self.refresh_mpd()
  File "dashproxy.py", line 129, in refresh_mpd
    self.handle_mpd(mpd)
  File "dashproxy.py", line 155, in handle_mpd
    self.ensure_downloader(mpd, rep_addr)
  File "dashproxy.py", line 173, in ensure_downloader
    downloader.handle_mpd(mpd, self.get_base_url(mpd))
  File "dashproxy.py", line 211, in handle_mpd
    segments = copy.deepcopy(segment_timeline.findall('mpd:S', ns))
AttributeError: 'NoneType' object has no attribute 'findall'

Unfortunately it seems that dash-proxy does not support such SegmentTemplate (without SegmentTimeline) which is used in this manifest.

I will try to fix that.

**Comment by przemyslaw-gorszkowski-red** [comment]
@kevan1 : I provided a fix for your manifest on my branch: https://github.com/przemyslaw-gorszkowski-red/dash-proxy/tree/master_branch, please try to download your content with my modification

**Comment by Essam311** [comment]
@przemyslaw-gorszkowski-red I'm trying to download the subtitles from this link but the script does not work

https://cdxaws-ak.akamaized.net/out/v1/55ceb00a9faf44258853629702fd6cb4/469c706849ff410385e5d65308566647/5e2a57fc0380466b9864849ce3f168ea/manifest.mpd

I can download the audio and the video from the link using

https://github.com/nilaoda/N_m3u8DL-CLI

which is not supporting downloading the subtitles, I only need the unencrypted subtitles. Could you try to modify the script? Thanks.

**Comment by przemyslaw-gorszkowski-red** [comment]
@Essam311 are you still interested in to get the script which is able to download subtitles from:

https://cdxaws-ak.akamaized.net/out/v1/55ceb00a9faf44258853629702fd6cb4/469c706849ff410385e5d65308566647/5e2a57fc0380466b9864849ce3f168ea/manifest.mpd ?


I fixed the existing script and will provide it this week on my fork.



________________________________
