### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'find'

### ISSUE THREAD

**Issue by bradisbell** [Viblast/dash-proxy#5]
The utilty doesn't seem to work for some of the DASH-IF test assets:

    python dashproxy.py "https://dash.akamaized.net/dash264/TestCasesHD/MultiPeriod_OnDemand/TwoPeriods/TwoPeriod_OnDemand.mpd" -o .

```
[32mRunning dash proxy for stream https://dash.akamaized.net/dash264/TestCasesHD/MultiPeriod_OnDemand/
TwoPeriods/TwoPeriod_OnDemand.mpd. Output goes in .[0m
[32mmpd=[<Element '{urn:mpeg:dash:schema:mpd:2011}Period' at 0x5675890>, <Element '{urn:mpeg:dash:sche
ma:mpd:2011}Period' at 0x567e470>][0m
[32mStarting a downloader for Representation (period=0 adaptation-set=0 representation=0)[0m
Traceback (most recent call last):
  File "dashproxy.py", line 289, in <module>
    main()
  File "dashproxy.py", line 286, in main
    run(args)
  File "dashproxy.py", line 275, in run
    return proxy.run()
  File "dashproxy.py", line 115, in run
    self.refresh_mpd()
  File "dashproxy.py", line 129, in refresh_mpd
    self.handle_mpd(mpd)
  File "dashproxy.py", line 155, in handle_mpd
    self.ensure_downloader(mpd, rep_addr)
  File "dashproxy.py", line 173, in ensure_downloader
    downloader.handle_mpd(mpd, self.get_base_url(mpd))
  File "dashproxy.py", line 204, in handle_mpd
    segment_timeline = self.mpd.segment_timeline(self.rep_addr)
  File "dashproxy.py", line 77, in segment_timeline
    return self.segment_template(rep_addr).find('mpd:SegmentTimeline', ns)
AttributeError: 'NoneType' object has no attribute 'find'
```

Python 2.7.14 on Windows 10 x64

**Comment by yolanda123a** [comment]
i have the same issue in python 3 windows 10 x64 and ubuntu windows shell virtualization.
any idea how solve error
i have python pip and dependence installed
what more i should install for this
thanks

**Comment by radvaz** [comment]
I had the same kind of errors when tying to download a live streaming content:

Traceback (most recent call last):
File "dashproxy.py", line 289, in
main()
File "dashproxy.py", line 286, in main
run(args)
File "dashproxy.py", line 275, in run
return proxy.run()
File "dashproxy.py", line 115, in run
self.refresh_mpd()
File "dashproxy.py", line 128, in refresh_mpd
mpd = xml.etree.ElementTree.fromstring(r.text)
File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1311, in XML
parser.feed(text)
File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1657, in feed
self._parser.Parse(data, 0)
UnicodeEncodeError: 'ascii' codec can't encode character u'\xe3' in position 116169: ordinal not in range(128)

How could we fix this issue?
