### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by ovidiugabriel** [Viblast/dash-proxy#6]
IndexError: list index out of range

```
>> $ ./dashproxy.py http://yt-dash-mse-test.commondatastorage.googleapis.com/media/car-20120827-manifest.mpd -o .
Running dash proxy for stream http://yt-dash-mse-test.commondatastorage.googleapis.com/media/car-20120827-manifest.mpd. Output goes in .
mpd=[]
Traceback (most recent call last):
  File "./dashproxy.py", line 289, in <module>
    main()
  File "./dashproxy.py", line 286, in main
    run(args)
  File "./dashproxy.py", line 275, in run
    return proxy.run()
  File "./dashproxy.py", line 115, in run
    self.refresh_mpd()
  File "./dashproxy.py", line 129, in refresh_mpd
    self.handle_mpd(mpd)
  File "./dashproxy.py", line 150, in handle_mpd
    period = periods[0]
IndexError: list index out of range
```

**Comment by radvaz** [comment]
I had the same kind of errors when tying to download a live streaming content:

Traceback (most recent call last):
  File "dashproxy.py", line 289, in <module>
    main()
  File "dashproxy.py", line 286, in main
    run(args)
  File "dashproxy.py", line 275, in run
    return proxy.run()
  File "dashproxy.py", line 115, in run
    self.refresh_mpd()
  File "dashproxy.py", line 128, in refresh_mpd
    mpd = xml.etree.ElementTree.fromstring(r.text)
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1311, in XML
    parser.feed(text)
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1657, in feed
    self._parser.Parse(data, 0)
UnicodeEncodeError: 'ascii' codec can't encode character u'\xe3' in position 116169: ordinal not in range(128)

How could we fix this issue?
